- hosts: all
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/vault.yml
    - group_vars/datacenter_name.yml
  roles:
    - common
    - network
    - config
    - datastore
    - scratch
    - iscsi-vmk
    - iscsi
