- name: Add NFS datastores to host
  community.vmware.vmware_host_datastore:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    datastore_name: '{{ item.name }}'
    datastore_type: '{{ item.type }}'
    nfs_server: '{{ item.server }}'
    nfs_path: '{{ item.path }}'
    nfs_ro: no        
    state: present
  loop: '{{ datastores }}'