- name: Enable iSCSI of ESXi
  community.vmware.vmware_host_iscsi:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    state: enabled
- name: Add VMKernels to iSCSI config of ESXi
  community.vmware.vmware_host_iscsi:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    iscsi_config:
      vmhba_name: vmhba64
      port_bind: '{{ iscsi_vmk }}'
    state: present
- name: Gather iSCSI configuration information of ESXi host
  community.vmware.vmware_host_iscsi_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
  register: iscsi_info
- name: Add Target to iSCSI config
  community.vmware.vmware_host_iscsi:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    iscsi_config:
      vmhba_name: vmhba64
      static_target:
        iscsi_name: '{{ item.iscsi_name }}'
        address: '{{ item.address }}'
    state: present
  loop: '{{ targets }}'
- name: Add Auth to iSCSI config
  community.vmware.vmware_host_iscsi:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    iscsi_config:
      vmhba_name: vmhba64
      static_target:
        iscsi_name: '{{ item.iscsi_name }}'
        address: '{{ item.address }}'
        authentication:
            chap_inherited: no
            chap_auth_enabled: yes
            chap_authentication_type: chapRequired
            chap_name: '{{ iscsi_info.iscsi_properties.iscsi_name }}'
            chap_secret: '{{ item.chap_secret }}'
            mutual_chap_inherited: no
            mutual_chap_authentication_type: chapRequired
            mutual_chap_name: '{{ iscsi_info.iscsi_properties.iscsi_name }}'
            mutual_chap_secret: '{{ item.mutual_chap_secret }}'
    state: present
  loop: '{{ targets }}'
- name: Recan HBA's
  community.vmware.vmware_host_scanhba:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    refresh_storage: true