- name: Add vmkernel adapters for iSCSI
  community.vmware.vmware_vmkernel:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: false
    dvswitch_name: '{{ dswitch }}'
    portgroup_name: '{{ item.name }}'
    mtu: '{{ item.mtu }}'
    network:
      ip_address: '{{ item.ip_address }}'
      subnet_mask: '{{ item.subnet_mask }}'
      type: static
    state: present
  loop: '{{ vmkiscsi }}'